AllCops:
  Exclude:
    - 'bin/**'
    - 'config/environments/**/*'
    - 'config/initializers/**/*'
    - 'db/fixtures/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'node_modules/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'config.ru'
    - 'config/**/*'
    - 'Rakefile'

StringLiterals:
  EnforcedStyle: double_quotes

Style/AsciiComments:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/WordArray:
  Enabled: false

Metrics/BlockLength:
  Max: 100

Metrics/LineLength:
  Max: 100
