version: 0.2

env:
  parameter-store:
    rails_master_key: rails_master_key
    docker_hub_password: docker_hub_password

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo Logging in to Docker Hub...
      - echo $docker_hub_password | docker login -u tynmarket --password-stdin
  build:
    commands:
      - echo Build started on `date`
      - printenv
      - echo Building the Docker image...
      - git rev-parse HEAD
      - SKIP_BUILD=false
      - CODEBUILD_VERSION=`echo $CODEBUILD_SOURCE_VERSION | awk -F/ '{print $1}'`; if [ $CODEBUILD_VERSION = "pr" ];then SKIP_BUILD=true;fi
      - echo $SKIP_BUILD
      - $SKIP_BUILD || BUILD_BRANCH=`echo $CODEBUILD_WEBHOOK_HEAD_REF | awk -F/ '{print $3}'`
      - if [ "$BUILD_BRANCH" = "master" ];then IMAGE_TAG=latest;else IMAGE_TAG=$BUILD_BRANCH;fi
      - echo $IMAGE_TAG
      - $SKIP_BUILD || docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG --build-arg rails_master_key=$rails_master_key .
      - $SKIP_BUILD || echo "docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG"
      - $SKIP_BUILD || docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - $SKIP_BUILD || echo Build completed on `date`
      - $SKIP_BUILD || echo Pushing the Docker image...
      - $SKIP_BUILD || docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
