# https://circleci.com/docs/2.0/language-ruby/
version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
        environment:
          RAILS_ENV: test
          TZ: Asia/Tokyo
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - imarket-bundle-{{ checksum "Gemfile.lock" }}

      - run:
          name: bundle install
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      # Store bundle cache
      - save_cache:
          key: imarket-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Restore yarn cache
      - restore_cache:
          keys:
            - imarket-yarn-{{ checksum "yarn.lock" }}

      - run:
          name: yarn install
          command: yarn install --cache-folder ~/.cache/yarn

      # Store yarn cache
      - save_cache:
          key: imarket-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      # Check type
      - run:
          name: npx tsc
          command: npx tsc

      # Run eslint
      - run:
          name: yarn lint
          command: yarn lint

      # Build assets
      - run:
          name: yarn build
          command: yarn build

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s

      - run: cp config/database.yml.circleci config/database.yml
      - run: bundle exec rake db:create db:schema:load

      - run:
          name: bin/rubocop
          command: bin/rubocop

      - run:
          name: Run rspec
          command: |
            bundle exec rspec --format progress \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml
      # collect reports
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results
          destination: test_results
