# https://circleci.com/docs/2.0/language-ruby/
version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          RAILS_ENV: test
          TZ: Asia/Tokyo
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - spider-bundle-{{ checksum "Gemfile.lock" }}

      - run:
          name: bundle install
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      # Store bundle cache
      - save_cache:
          key: spider-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Only necessary if app uses webpacker or yarn in some other way
      - restore_cache:
          keys:
            - coffeehub-yarn-{{ checksum "yarn.lock" }}

      - run:
          name: yarn install
          command: yarn install --cache-folder ~/.cache/yarn

      # Store yarn / webpacker cache
      - save_cache:
          key: coffeehub-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s

      - run: cp config/database.yml.circleci config/database.yml
      - run: bundle exec rake db:create db:schema:load

      - run:
          name: Run rspec
          command: |
            bundle exec rspec --format RspecJunitFormatter \
                              --out test_results/rspec.xml

      # Save test results for timing analysis
      - store_test_results:
          path: test_results
